### ISSUE TITLE
No graphs anymore?

### ISSUE THREAD

**Issue by WiseWomanVP** [j-fu/coronaplot#2]
Currently, nothing is showing ;) Hope you get it back to work soon!

**Comment by j-fu** [comment]
Hi 
Ah you seem to link the plots directly ?
I re-organized the page a bit. It is now served as j-fu.github.io/coronaplot and has a German and an English version. 
This is why the plots now are in the docs/ subdirectory.
But I see your point. I will maintain the plots now twice, in the root folder and under docs/ 

All explanations however will stay in docs.
Please have a look at the growth rate plot as well...

**Comment by WiseWomanVP** [comment]
Not only that, I posted the link a number of places (and was so happy it was in English) When I follow j-fu.github.io/coronaplot I end up on a German page (which I understand, but not my friends in the States). I would only expect documentation in a directory called docs ;) I see you now have links and an extra notice that one can click on the headings. Thanks! Appreciate your work!

**Comment by j-fu** [comment]
Yeah the docs thing is what github has as one possible standard for hosting github pages. Another one was to serve directly from the root - sorry for overdoing this.
Stay healthy!
